// Extracts GLSL + data declarations VERBATIM from the legacy HTML into packages/core.
// Never retype shader strings — transcription bugs are invisible until render (roadmap §8).
// Run: node scripts/extract-glsl.mjs
import { readFileSync, writeFileSync } from 'node:fs';

const HTML = 'plasma_studio (4).html';
const html = readFileSync(HTML, 'utf8');

const sm = html.match(/<script>([\s\S]*?)<\/script>/);
if (!sm) throw new Error('no <script> block found');
const src = sm[1];

// Scan the balanced expression after `const NAME=` up to the depth-0 terminating ';'.
// Handles '...', "...", `...` template literals and ${} re-entry.
function extractDecl(name) {
  const re = new RegExp('const\\s+' + name + '\\s*=');
  const m = re.exec(src);
  if (!m) throw new Error('declaration not found: ' + name);
  let i = m.index + m[0].length;
  while (/\s/.test(src[i])) i++;
  const start = i;
  const stack = [];
  let inStr = null;
  while (i < src.length) {
    const c = src[i];
    if (inStr) {
      if (c === '\\') { i += 2; continue; }
      if (inStr === '`') {
        if (c === '`') { inStr = null; i++; continue; }
        if (c === '$' && src[i + 1] === '{') { stack.push('${'); inStr = null; i += 2; continue; }
      } else if (c === inStr) { inStr = null; i++; continue; }
      i++; continue;
    }
    if (c === "'" || c === '"' || c === '`') { inStr = c; i++; continue; }
    if (c === '(' || c === '[' || c === '{') { stack.push(c); i++; continue; }
    if (c === ')' || c === ']' || c === '}') {
      const top = stack[stack.length - 1];
      if (top === '${' && c === '}') { stack.pop(); inStr = '`'; i++; continue; }
      stack.pop(); i++; continue;
    }
    if (c === ';' && stack.length === 0) break;
    i++;
  }
  return src.slice(start, i).trim();
}

const get = (n) => extractDecl(n);

// Extract a `function NAME(...) { ... }` declaration verbatim (balanced braces).
function extractFunc(name) {
  const re = new RegExp('function\\s+' + name + '\\s*\\(');
  const m = re.exec(src);
  if (!m) throw new Error('function not found: ' + name);
  let i = m.index;
  // advance to the opening brace of the body
  let bodyStart = src.indexOf('{', i);
  let depth = 0, inStr = null, j = bodyStart;
  for (; j < src.length; j++) {
    const c = src[j];
    if (inStr) {
      if (c === '\\') { j++; continue; }
      if (c === inStr) inStr = null;
      continue;
    }
    if (c === "'" || c === '"' || c === '`') { inStr = c; continue; }
    if (c === '{') depth++;
    else if (c === '}') { depth--; if (depth === 0) { j++; break; } }
  }
  return src.slice(i, j);
}
const fn = (n) => extractFunc(n);

const shaders = `// AUTO-GENERATED by scripts/extract-glsl.mjs — DO NOT EDIT BY HAND.
// GLSL copied verbatim from the legacy HTML. Regenerate after any shader change.
/* eslint-disable */

export const VERT = ${get('VERT')};

export const FLOW_FRAG = ${get('FLOW_FRAG')};

export const PRE_A = ${get('PRE_A')};

export const PRE_B = ${get('PRE_B')};

export const MAIN = ${get('MAIN')};

export const GRAD_MAIN = ${get('GRAD_MAIN')};

export const FIELDS = ${get('FIELDS')};

export const MATERIALS = ${get('MATERIALS')};

export const FIELD_NAMES = FIELDS.map((f) => f.name);
export const MATERIAL_NAMES = MATERIALS.map((m) => m.name);

// Ramp fields use no fbm (clean gradients): Linear/Radial/Conic — see roadmap §3.
// buildFrag assembles: PRE_A + field + PRE_B + material + MAIN (declaration order matters, gotcha §4.1).
export function buildFrag(fieldIdx: number, matIdx: number): string {
  return PRE_A + FIELDS[fieldIdx].src + '\\n' + PRE_B + MATERIALS[matIdx].src + '\\n' + MAIN;
}
`;

const data = `// AUTO-GENERATED by scripts/extract-glsl.mjs — DO NOT EDIT BY HAND.
// Data copied verbatim from the legacy HTML.
/* eslint-disable */

export const SHAPES = ${get('SHAPES')};

export const GRADIENTS = ${get('GRADIENTS')};

export const NUMCFG = ${get('NUMCFG')};

export const SHAPE_NAMES = SHAPES.map((s) => s.name);
`;

// THEMES are closures over helpers (hsl2hex/generatePalette/RR/pick) — extract them too.
// @ts-nocheck: this is a verbatim JS port (legacy helpers are loosely typed by design).
const themes = `// AUTO-GENERATED by scripts/extract-glsl.mjs — DO NOT EDIT BY HAND.
// Theme "vibes" + palette helpers copied verbatim from the legacy HTML.
// @ts-nocheck
/* eslint-disable */

export ${fn('hsl2hex')}

export ${fn('generatePalette')}

export const RR = ${get('RR')};

export const pick = ${get('pick')};

export const THEMES = ${get('THEMES')};

export const THEME_NAMES = Object.keys(THEMES);
`;

writeFileSync('packages/core/src/plasma/shaders.ts', shaders);
writeFileSync('packages/core/src/plasma/data.ts', data);
writeFileSync('packages/core/src/plasma/themes.ts', themes);

// Report counts so a human can eyeball parity.
const countTop = (lit) => (lit.match(/\{name:/g) || []).length;
console.log('FIELDS objects   :', countTop(get('FIELDS')));
console.log('MATERIALS objects:', countTop(get('MATERIALS')));
console.log('SHAPES objects   :', countTop(get('SHAPES')));
console.log('GRADIENTS keys   :', (get('GRADIENTS').match(/:/g) || []).length, '(approx)');
console.log('wrote shaders.ts + data.ts');
