// AUTO-GENERATED by scripts/extract-glsl.mjs — DO NOT EDIT BY HAND.
// Data copied verbatim from the legacy HTML.
/* eslint-disable */

export const SHAPES = [{name:"Free"},{name:"Linear"},{name:"Circle"},{name:"Angular"},{name:"Spiral"},{name:"Polar"},{name:"Mirror"}];

export const GRADIENTS = {
  'Sunset':['#0d0221','#ff5e62','#ff9966','#ffd200'],
  'Ocean':['#021b3a','#0b6fb8','#00e0d0','#9bf6e0'],
  'Aurora':['#011627','#1b9aaa','#36e07a','#e0f7ff'],
  'Neon':['#0a0014','#ff00e5','#7a00ff','#00fff0'],
  'Fire':['#1a0000','#ff3c00','#ff9a00','#ffe14a'],
  'Pastel dream':['#ffd1dc','#c1f0f6','#d9c2f0','#fff3b0'],
  'Candy':['#2b0a3d','#ff3c9e','#ffd24a','#36e07a','#67d4ff'],
  'Mint':['#03251b','#2fbf71','#a8e6cf'],
  'Mono blue':['#0a0f1f','#5566aa','#cdd6f4'],
  'Grayscale':['#0a0a0a','#7a7a7a','#f2f2f2'],
  'Vapor':['#1a0033','#ff71ce','#01cdfe','#b967ff','#fffb96'],
  'Ember':['#10060b','#7a1f3d','#e0563b','#ffb15a']
};

export const NUMCFG = { speed:[100,2,''], scale:[1,0,'%'], swirl:[100,2,''], turb:[100,2,''], flowAng:[1,0,'°'],
  flowAmt:[100,2,''], gravity:[100,2,''], cover:[100,2,''], contrast:[100,2,''], vis:[100,2,''], noise:[100,2,''], rotate:[1,0,'°'], cursorStr:[100,2,''], cursorSize:[100,2,''], cursorTrail:[100,2,''], cursorChurn:[100,2,''], cursorLag:[100,2,''] };

export const SHAPE_NAMES = SHAPES.map((s) => s.name);
