// AUTO-GENERATED by scripts/extract-glsl.mjs — DO NOT EDIT BY HAND.
// GLSL copied verbatim from the legacy HTML. Regenerate after any shader change.
/* eslint-disable */

export const VERT = `attribute vec2 a_pos; varying vec2 v_uv;
void main(){ v_uv=a_pos*0.5+0.5; gl_Position=vec4(a_pos,0.0,1.0); }`;

export const FLOW_FRAG = `precision highp float;
uniform sampler2D u_prev; uniform float u_fall; uniform float u_diss; uniform float u_aspect; uniform vec2 u_fmouse; uniform vec2 u_fvel; uniform float u_present;
varying vec2 v_uv;
void main(){
  vec4 c=texture2D(u_prev, v_uv);
  vec2 vel=(c.rg-0.5)*2.0; float str=c.b;
  vel*=u_diss; str*=u_diss;
  vec2 cur=v_uv-u_fmouse; cur.x*=u_aspect;
  float fall=smoothstep(u_fall,0.0,length(cur));
  vec2 sv=clamp(u_fvel,-1.0,1.0);
  float ss=max(1.0-pow(1.0-min(1.0,length(u_fvel)),3.0), u_present);
  vel=mix(vel,sv,fall); str=mix(str,ss,fall);
  gl_FragColor=vec4(vel*0.5+0.5, str, 1.0);
}`;

export const PRE_A = `
precision highp float;
uniform float u_time; uniform vec2 u_res; uniform float u_speed; uniform float u_scale;
uniform vec3 u_colors[8]; uniform int u_count; uniform vec3 u_bg;
uniform float u_detail; uniform float u_turb; uniform float u_swirl; uniform vec2 u_flow; uniform float u_vis; uniform float u_cover; uniform float u_noise; uniform float u_gravity; uniform int u_shape; uniform float u_contrast; uniform vec2 u_center; uniform float u_rot; uniform vec2 u_mouse; uniform float u_mouseAmt; uniform float u_cm[5]; uniform float u_mouseRad; uniform float u_curChurn; uniform float u_curStr; uniform sampler2D u_fmap;
varying vec2 v_uv;
mat2 rot(float a){ float c=cos(a),s=sin(a); return mat2(c,-s,s,c); }
vec2 shapeXf(vec2 p){
  float r=length(p); float a=atan(p.y,p.x);
  if(u_shape==1){ return vec2(p.x*0.9, p.y*0.08); }                                  // Linear bands
  if(u_shape==2){ return vec2(r*1.7, 0.0); }                                         // Circle (seamless concentric)
  if(u_shape==3){ return vec2(cos(a),sin(a))*1.3; }                                  // Angular wheel (seamless loop)
  if(u_shape==4){ float ph=a+r*2.6; return vec2(cos(ph),sin(ph))*1.3 + vec2(r*0.2,0.0); } // Spiral (seamless)
  if(u_shape==5){ return vec2(cos(a)*1.2, sin(a)*1.2) + vec2(r*1.5,0.0); }            // Polar (seamless angle+radius)
  if(u_shape==6){ float seg=6.28318/6.0; a=mod(a,seg); a=abs(a-seg*0.5); return vec2(cos(a),sin(a))*r; } // Mirror
  return p;
}
float hash(vec2 p){ p=fract(p*vec2(123.34,456.21)); p+=dot(p,p+45.32); return fract(p.x*p.y); }
float noise(vec2 p){ vec2 i=floor(p),f=fract(p);
  float a=hash(i),b=hash(i+vec2(1.,0.)),c=hash(i+vec2(0.,1.)),d=hash(i+vec2(1.,1.));
  vec2 u=f*f*(3.0-2.0*f); return mix(mix(a,b,u.x),mix(c,d,u.x),u.y); }
float fbm(vec2 p){ float v=0.0,a=0.5; for(int i=0;i<5;i++){ v+=a*noise(p); p=rot(0.5)*p*2.0; a*=0.5; } return v; }
vec2 asp(){ vec2 uv=v_uv*2.0-1.0; uv.x*=u_res.x/u_res.y;
  if(u_mouseAmt>0.001){ vec3 fmp=texture2D(u_fmap, v_uv).rgb; vec2 fv=(fmp.rg-0.5)*2.0; float fst=clamp(fmp.b,0.0,1.0);
    if(u_cm[0]>0.5){ float fwx=sin(uv.y*2.6+u_time*0.7)*0.6 + sin(uv.y*1.3-u_time*0.4)*0.4; float fwy=sin(uv.x*2.3-u_time*0.6)*0.6 + sin(uv.x*1.1+u_time*0.5)*0.4;
      uv-= fv*u_curStr*1.4 + vec2(fwx,fwy)*fst*u_mouseRad*u_curChurn*0.6; }
    if(u_cm[1]>0.5){ float cell=0.12; vec2 q=(floor(uv/cell)+0.5)*cell; uv=mix(uv,q,smoothstep(0.0,1.0,fst)); } }
  uv-=u_center; uv*=u_scale;
  float cr=cos(u_rot), sr=sin(u_rot); uv=vec2(cr*uv.x - sr*uv.y, sr*uv.x + cr*uv.y);
  float ft=u_time*u_speed; uv+=u_flow*ft;
  float fa=length(u_flow);
  if(fa>0.0001){ vec2 dr=u_flow/fa; vec2 pp=vec2(-dr.y,dr.x);
    uv += pp*sin(dot(uv,dr)*3.0 - ft*2.5)*fa*0.9;
    uv += dr*cos(dot(uv,pp)*2.2 + ft*1.7)*fa*0.5; }
  uv=shapeXf(uv);
  uv.y += u_gravity*0.7*sin(uv.x*1.6); uv.x += u_gravity*0.25*sin(uv.y*1.3); return uv; }
vec3 pal(float t){
  float n=float(u_count); if(n<1.0) n=1.0; t=fract(t)*n;
  float fseg=floor(t); float f=t-fseg;
  int i0=int(mod(fseg,n)); int i1=int(mod(fseg+1.0,n));
  vec3 c0=u_colors[0]; vec3 c1=u_colors[0];
  for(int k=0;k<8;k++){ if(k==i0) c0=u_colors[k]; if(k==i1) c1=u_colors[k]; }
  return mix(c0,c1,smoothstep(0.0,1.0,f));
}
vec3 ramp(float s){
  s=clamp(s,0.0,1.0); float n=float(u_count); if(n<2.0) return u_colors[0];
  float x=s*(n-1.0); float idx=floor(x); float f=x-idx;
  int i0=int(idx); int i1=i0+1;
  vec3 c0=u_colors[0]; vec3 c1=u_colors[0];
  for(int k=0;k<8;k++){ if(k==i0) c0=u_colors[k]; if(k==i1) c1=u_colors[k]; }
  return mix(c0,c1,smoothstep(0.0,1.0,f));
}
`;

export const PRE_B = `
vec3 calcNormal(vec2 uv, float t){
  float e=0.012; float c=plasma(uv,t);
  float dx=plasma(uv+vec2(e,0.0),t)-c; float dy=plasma(uv+vec2(0.0,e),t)-c;
  return normalize(vec3(-dx,-dy, e*7.0));
}
float blurP(vec2 uv,float t){ float s=plasma(uv,t);
  s+=plasma(uv+vec2(0.09,0.0),t); s+=plasma(uv-vec2(0.09,0.0),t);
  s+=plasma(uv+vec2(0.0,0.09),t); s+=plasma(uv-vec2(0.0,0.09),t); return s/5.0; }
vec3 screenb(vec3 a, vec3 b){ a=clamp(a,0.0,1.0); b=clamp(b,0.0,1.0); return 1.0-(1.0-a)*(1.0-b); }
vec3 ovl(vec3 c){ c=clamp(c,0.0,1.0); return mix(2.0*c*c, 1.0-2.0*(1.0-c)*(1.0-c), step(vec3(0.5),c)); }
`;

export const MAIN = `void main(){ vec3 e=max(effect(),0.0); float lum=max(max(e.r,e.g),e.b); float thr=(1.0-u_cover)*0.95; e*=smoothstep(thr,thr+0.18,lum); vec3 sc=screenb(u_bg,e); vec3 col=mix(u_bg, sc, u_vis); if(u_contrast>=1.0){ float amt=u_contrast-1.0; col=mix(col,ovl(col),min(amt,1.0)); col=mix(col,ovl(col),max(amt-1.0,0.0)); } else { col=(col-0.5)*u_contrast+0.5; } if(u_mouseAmt>0.001){ float ci=clamp(texture2D(u_fmap, v_uv).b*u_curStr,0.0,1.0); if(u_cm[4]>0.5){ col=mix(col,ovl(col),ci); } if(u_cm[3]>0.5){ col+=ci*0.6; } if(u_cm[2]>0.5){ col=mix(u_bg,col,clamp(ci*1.6,0.0,1.0)); } } float gr=(hash(gl_FragCoord.xy+fract(u_time*0.7))-0.5)*u_noise; col+=gr; gl_FragColor=vec4(col,1.0); }`;

export const GRAD_MAIN = `void main(){ vec3 c=gradient(); c=mix(u_bg,c,u_vis); float gr=(hash(gl_FragCoord.xy+fract(u_time*0.7))-0.5)*u_noise; c+=gr; gl_FragColor=vec4(c,1.0); }`;

export const FIELDS = [
{name:"Classic", src:`float plasma(vec2 uv,float t){ for(int i=0;i<3;i++){ uv=rot((0.3+t*0.04)*u_swirl)*uv; uv+=0.3*u_turb*sin(uv.yx*3.0*u_detail+t);} return sin(uv.x*3.0*u_detail)+sin(uv.y*3.0*u_detail+t)+sin((uv.x+uv.y)*2.0*u_detail); }`},
{name:"Deep Fold", src:`float plasma(vec2 uv,float t){ for(int i=0;i<6;i++){ uv=rot((0.25+t*0.03)*u_swirl)*uv; uv+=0.35*u_turb*sin(uv.yx*2.5*u_detail+t*0.8);} return sin(uv.x*2.0*u_detail)+sin(uv.y*2.5*u_detail+t)+sin(length(uv)*3.0*u_detail); }`},
{name:"Kaleidoscope", src:`float plasma(vec2 uv,float t){ float a=atan(uv.y,uv.x),r=length(uv); float seg=6.28318/6.0; a=mod(a,seg); a=abs(a-seg*0.5); uv=vec2(cos(a),sin(a))*r; for(int i=0;i<3;i++){ uv=rot((0.3+t*0.04)*u_swirl)*uv; uv+=0.3*u_turb*sin(uv.yx*3.0*u_detail+t);} return sin(uv.x*3.0*u_detail)+sin(uv.y*3.0*u_detail+t)+sin((uv.x+uv.y)*2.0*u_detail); }`},
{name:"Liquid", src:`float plasma(vec2 uv,float t){ uv*=0.6; for(int i=0;i<2;i++){ uv=rot((0.15+t*0.02)*u_swirl)*uv; uv+=0.45*u_turb*sin(uv.yx*1.3*u_detail+t*0.6);} return (sin(uv.x*1.3*u_detail)+sin(uv.y*1.3*u_detail+t*0.7))*1.6; }`},
{name:"Electric", src:`float plasma(vec2 uv,float t){ for(int i=0;i<3;i++){ uv=rot((0.3+t*0.05)*u_swirl)*uv; uv+=0.3*u_turb*sin(uv.yx*3.2*u_detail+t);} float v=sin(uv.x*3.2*u_detail)+sin(uv.y*3.2*u_detail+t)+sin((uv.x+uv.y)*2.2*u_detail); return (1.0-abs(v)*0.6)*2.6-1.3; }`},
{name:"Marble", src:`float plasma(vec2 uv,float t){ for(int i=0;i<4;i++){ uv=rot((0.28+t*0.03)*u_swirl)*uv; uv+=0.3*u_turb*sin(uv.yx*2.8*u_detail+t*0.9);} return (abs(sin(uv.x*3.0*u_detail)+sin(uv.y*3.0*u_detail+t)+sin((uv.x+uv.y)*2.0*u_detail))-1.0)*1.3; }`},
{name:"Vortex", src:`float plasma(vec2 uv,float t){ float r=length(uv); uv=rot(r*1.4*u_swirl - t*0.8)*uv; for(int i=0;i<3;i++){ uv=rot(0.3*u_swirl)*uv; uv+=0.3*u_turb*sin(uv.yx*3.0*u_detail+t);} return sin(uv.x*3.0*u_detail)+sin(uv.y*3.0*u_detail+t)+sin((uv.x+uv.y)*2.0*u_detail); }`},
{name:"Breathe", src:`float plasma(vec2 uv,float t){ float r=length(uv); float a=atan(uv.y,uv.x); float warp=u_turb*sin(a*4.0+t)*0.5; float rings=sin((r*5.0*u_detail - t*1.5)+warp*4.0); return rings*1.6 + sin(r*2.0*u_detail - t)*0.5; }`},
{name:"Shimmer", src:`float plasma(vec2 uv,float t){ uv*=1.6; for(int i=0;i<2;i++){ uv=rot((0.2+t*0.06)*u_swirl)*uv; uv+=0.18*u_turb*sin(uv.yx*6.0*u_detail+t*1.5);} return (sin(uv.x*7.0*u_detail)*sin(uv.y*7.0*u_detail+t) + sin((uv.x-uv.y)*5.0*u_detail+t))*1.4; }`},
{name:"Linear", src:`float plasma(vec2 uv,float t){ float ang=u_swirl*2.0; vec2 d=vec2(cos(ang),sin(ang)); return dot(uv,d)*2.2; }`},
{name:"Radial", src:`float plasma(vec2 uv,float t){ return length(uv)*2.6 - t*0.3; }`},
{name:"Conic", src:`float plasma(vec2 uv,float t){ float a=atan(uv.y,uv.x)+t*0.2; float tri=abs(fract(a*0.15915+0.5)*2.0-1.0); return tri*4.5; }`}
];

export const MATERIALS = [
{name:"Smooth", src:`vec3 effect(){ vec2 uv=asp(); float t=u_time*u_speed; float h=plasma(uv,t); return pal(h*0.22+t*0.04); }`},
{name:"Liquid Glass", src:`vec3 effect(){ vec2 uv=asp(); float t=u_time*u_speed; vec3 n=calcNormal(uv,t);
  vec2 refr=uv+n.xy*0.7; float b=plasma(refr,t);
  vec3 col=pal(b*0.2+t*0.08)*(0.35+0.45*smoothstep(-1.5,2.0,b));
  float fres=pow(1.0-n.z,2.5); col+=fres*vec3(0.85,0.92,1.0)*0.9;
  vec3 L=normalize(vec3(0.5,0.7,0.8)); col+=pow(max(dot(n,L),0.0),45.0)*1.3; return col; }`},
{name:"Chromatic", src:`vec3 effect(){ vec2 uv=asp(); float t=u_time*u_speed; vec3 n=calcNormal(uv,t); float a=0.3;
  float r=plasma(uv+n.xy*a,t), g=plasma(uv,t), bl=plasma(uv-n.xy*a,t);
  vec3 cr=pal(r*0.2+t*0.08), cg=pal(g*0.2+t*0.08), cb=pal(bl*0.2+t*0.08);
  vec3 col=vec3(cr.r,cg.g,cb.b); col+=pow(1.0-n.z,2.0)*0.45; return col; }`},
{name:"Liquid Metal", src:`vec3 effect(){ vec2 uv=asp(); float t=u_time*u_speed; vec3 n=calcNormal(uv,t);
  vec3 R=reflect(vec3(0.0,0.0,-1.0),n); float env=sin(R.x*5.0+t)+sin(R.y*5.0)+sin((R.x+R.y)*3.0);
  vec3 col=pal(env*0.18+0.5)*0.6; vec3 L=normalize(vec3(0.4,0.6,0.7));
  col+=pow(max(dot(n,L),0.0),60.0)*1.6; col+=pow(1.0-n.z,3.0)*vec3(0.8,0.85,0.95)*0.6; return col; }`},
{name:"Holographic", src:`vec3 effect(){ vec2 uv=asp(); float t=u_time*u_speed; vec3 n=calcNormal(uv,t); float h=plasma(uv,t);
  float fres=pow(1.0-n.z,1.4); vec3 col=pal(fres*2.2+h*0.12+t*0.06);
  col*=0.6+0.7*fres; col+=pow(1.0-n.z,5.0)*0.4; return col; }`},
{name:"Frosted", src:`vec3 effect(){ vec2 uv=asp(); float t=u_time*u_speed; float b=blurP(uv,t);
  vec3 col=mix(pal(b*0.18+t*0.06), vec3(0.85,0.88,0.95), 0.32); col*=0.5+0.45*smoothstep(-1.5,2.0,b); return col; }`},
{name:"Oil Slick", src:`vec3 effect(){ vec2 uv=asp(); float t=u_time*u_speed; vec3 n=calcNormal(uv,t); float h=plasma(uv,t);
  float band=h*0.5+n.z*2.0+length(n.xy)*3.0+t*0.1; vec3 col=pal(band); col*=0.5+0.6*smoothstep(-1.0,2.0,h); return col; }`},
{name:"Crystal", src:`vec3 effect(){ vec2 uv=asp(); float t=u_time*u_speed; vec3 n=calcNormal(uv,t);
  n=normalize(floor(n*5.0)/5.0+0.06); vec2 refr=uv+n.xy*0.8; float b=plasma(refr,t);
  vec3 col=pal(b*0.22+t*0.08)*(0.4+0.5*smoothstep(-1.5,2.0,b));
  col+=pow(1.0-n.z,2.0)*vec3(0.9,0.95,1.0)*0.8; vec3 L=normalize(vec3(0.5,0.6,0.7));
  col+=pow(max(dot(n,L),0.0),30.0)*1.2; return col; }`},
{name:"Pearl", src:`vec3 effect(){ vec2 uv=asp(); float t=u_time*u_speed; vec3 n=calcNormal(uv,t); float h=plasma(uv,t);
  float fres=pow(1.0-n.z,2.0); vec3 sheen=pal(h*0.1+fres*1.2+t*0.05);
  vec3 col=mix(vec3(0.78,0.76,0.82), sheen, 0.55); col*=0.6+0.5*smoothstep(-1.5,2.0,h); col+=fres*0.3; return col; }`},
{name:"Neon Gel", src:`vec3 effect(){ vec2 uv=asp(); float t=u_time*u_speed; vec3 n=calcNormal(uv,t); float h=plasma(uv,t);
  vec3 base=pal(h*0.2+t*0.1); float glow=0.5+0.5*sin(h*1.5+t);
  vec3 col=base*glow;
  vec3 L=normalize(vec3(0.4,0.6,0.85)); float spec=pow(max(dot(n,L),0.0),18.0);
  col+=spec*1.15; col+=pow(1.0-max(n.z,0.0),2.5)*base*0.6;
  col=col/(1.0+col*0.35); return col; }`},
{name:"Prism", src:`vec3 effect(){ vec2 uv=asp(); float t=u_time*u_speed; vec3 n=calcNormal(uv,t); float a=0.55; vec3 col;
  col.r=pal(plasma(uv+n.xy*a,t)*0.2+t*0.08).r; col.g=pal(plasma(uv,t)*0.2+t*0.08).g; col.b=pal(plasma(uv-n.xy*a,t)*0.2+t*0.08).b;
  float edge=pow(length(n.xy),0.6); col+=edge*pal(n.x*2.0+n.y*2.0+t*0.1)*0.7; return col; }`},
{name:"Warped", src:`vec3 effect(){ vec2 uv=asp(); float t=u_time*u_speed; float h=plasma(uv,t);
  float hue=h*0.3 + fbm(uv*1.4+vec2(t*0.1,0.0))*0.5 + t*0.05; return pal(hue); }`},
{name:"Mesh", src:`vec3 effect(){ vec2 uv=asp(); float t=u_time*u_speed; float h=plasma(uv,t);
  return pal(h*0.14 + t*0.03); }`},
{name:"Aurora", src:`vec3 effect(){ vec2 uv=asp(); float t=u_time*u_speed; float h=plasma(uv,t);
  float f=clamp(h*0.18+0.5,0.0,1.0); f=pow(f,1.2); return ramp(f); }`}
];

export const FIELD_NAMES = FIELDS.map((f) => f.name);
export const MATERIAL_NAMES = MATERIALS.map((m) => m.name);

// Ramp fields use no fbm (clean gradients): Linear/Radial/Conic — see roadmap §3.
// buildFrag assembles: PRE_A + field + PRE_B + material + MAIN (declaration order matters, gotcha §4.1).
export function buildFrag(fieldIdx: number, matIdx: number): string {
  return PRE_A + FIELDS[fieldIdx].src + '\n' + PRE_B + MATERIALS[matIdx].src + '\n' + MAIN;
}
