// AUTO-GENERATED by scripts/extract-glsl.mjs — DO NOT EDIT BY HAND.
// Theme "vibes" + palette helpers copied verbatim from the legacy HTML.
// @ts-nocheck
/* eslint-disable */

export function hsl2hex(h,s,l){ h=((h%360)+360)%360/360; const a=s*Math.min(l,1-l);
  const f=n=>{ const k=(n+h*12)%12; const c=l-a*Math.max(-1,Math.min(k-3,9-k,1)); return ('0'+Math.round(255*c).toString(16)).slice(-2); };
  return '#'+f(0)+f(8)+f(4); }

export function generatePalette(mode){ const base=Math.random()*360, S=0.5+Math.random()*0.38, out=[];
  const mk=(h,l)=>hsl2hex(h,S,l);
  if(mode==='analogous'){ [-40,-20,0,20,40].forEach((d,i)=>out.push(mk(base+d,0.38+i*0.1))); }
  else if(mode==='complementary'){ out.push(mk(base,0.34),mk(base,0.58),mk(base+180,0.5),mk(base+180,0.72)); }
  else if(mode==='triadic'){ out.push(mk(base,0.5),mk(base+120,0.55),mk(base+240,0.5)); }
  else if(mode==='mono'){ [0.18,0.38,0.58,0.8].forEach(l=>out.push(mk(base,l))); }
  else { const n=3+Math.floor(Math.random()*3); for(let i=0;i<n;i++) out.push(mk(Math.random()*360,0.34+Math.random()*0.46)); }
  return out; }

export const RR = (a,b)=>a+Math.random()*(b-a);

export const pick = a=>a[Math.floor(Math.random()*a.length)];

export const THEMES = {
  'Cosmos':()=>({field:pick(['Marble','Liquid','Vortex']),mat:pick(['Neon Gel','Frosted','Smooth']),shape:'Free',
    palette:['#06021a','#3b1f8f','#9a3bd1','#ff4fd8','#36d6ff','#eafcff'].slice(0,4+Math.floor(Math.random()*2)),
    bg:'#04010f',speed:RR(0.18,0.32),scalePct:RR(110,180),swirl:RR(0.4,0.7),turb:RR(0.6,1.0),flowAmt:RR(0.05,0.18),flowAng:RR(0,360),cover:RR(0.28,0.42),contrast:RR(1.15,1.4),grav:0,noise:RR(0.35,0.6),rot:RR(0,360)}),
  'Stardust':()=>({field:'Shimmer',mat:pick(['Neon Gel','Crystal']),shape:'Free',
    palette:['#0a0618','#7b6cff','#c9b6ff','#ffffff'],bg:'#03030a',speed:RR(0.12,0.25),scalePct:RR(60,110),swirl:RR(0.2,0.5),turb:RR(0.7,1.0),flowAmt:RR(0,0.1),flowAng:RR(0,360),cover:RR(0.18,0.3),contrast:RR(1.1,1.3),grav:RR(0,0.2),noise:RR(0.5,0.7),rot:0}),
  'Black Hole':()=>({field:'Vortex',mat:pick(['Liquid Metal','Chromatic','Oil Slick']),shape:pick(['Spiral','Polar']),
    palette:['#000000','#3a0d4f','#b3203b','#ff7a18','#ffd86b'],bg:'#000005',speed:RR(0.2,0.4),scalePct:RR(90,150),swirl:RR(0.7,1.0),turb:RR(0.4,0.8),flowAmt:0,flowAng:0,cover:RR(0.45,0.7),contrast:RR(1.3,1.7),grav:0,noise:RR(0.15,0.35),rot:RR(0,360),center:[0,0]}),
  'Light Ray':()=>({field:'Conic',mat:pick(['Holographic','Prism','Smooth']),shape:pick(['Angular','Free']),
    palette:['#001018','#1b9aaa','#9be7ff','#fff3b0','#ffffff'],bg:'#02060c',speed:RR(0.15,0.3),scalePct:RR(90,140),swirl:RR(0,0.4),turb:0,flowAmt:0,flowAng:0,cover:RR(0.6,0.9),contrast:RR(1.2,1.5),grav:0,noise:RR(0.1,0.3),rot:RR(0,360),center:[RR(-0.3,0.3),RR(-0.2,0.2)]}),
  'Epic':()=>({field:pick(['Electric','Deep Fold','Liquid']),mat:pick(['Holographic','Oil Slick','Chromatic']),shape:'Free',
    palette:generatePalette(pick(['triadic','complementary'])),bg:'#05030d',speed:RR(0.4,0.8),scalePct:RR(90,150),swirl:RR(0.6,1.0),turb:RR(0.6,1.0),flowAmt:RR(0.1,0.3),flowAng:RR(0,360),cover:RR(0.7,1.0),contrast:RR(1.4,1.9),grav:RR(-0.3,0.3),noise:RR(0,0.15),rot:RR(0,360)}),
  'Aurora':()=>({field:'Liquid',mat:'Aurora',shape:'Free',
    palette:['#011627','#0b3d91','#1b9aaa','#36e07a','#e0f7ff'],bg:'#01040c',speed:RR(0.18,0.32),scalePct:RR(110,160),swirl:RR(0.4,0.7),turb:RR(0.5,0.8),flowAmt:RR(0.1,0.2),flowAng:RR(70,110),cover:RR(0.45,0.65),contrast:RR(1.1,1.35),grav:RR(-0.2,0.1),noise:RR(0.1,0.3),rot:0}),
  'Ember':()=>({field:'Marble',mat:pick(['Liquid Metal','Oil Slick','Neon Gel']),shape:'Free',
    palette:['#10060b','#7a1f3d','#e0563b','#ffb15a','#ffe7a0'],bg:'#0a0402',speed:RR(0.15,0.3),scalePct:RR(110,170),swirl:RR(0.3,0.6),turb:RR(0.6,0.9),flowAmt:RR(0.05,0.15),flowAng:RR(80,100),cover:RR(0.5,0.75),contrast:RR(1.2,1.5),grav:RR(0.2,0.5),noise:RR(0.2,0.4),rot:0}),
  'Vaporwave':()=>({field:pick(['Liquid','Breathe']),mat:'Holographic',shape:pick(['Linear','Free']),
    palette:['#1a0033','#ff71ce','#01cdfe','#b967ff','#fffb96'],bg:'#0a021a',speed:RR(0.2,0.4),scalePct:RR(90,150),swirl:RR(0.3,0.6),turb:RR(0.3,0.6),flowAmt:RR(0.1,0.25),flowAng:pick([0,180]),cover:RR(0.6,0.9),contrast:RR(1.2,1.5),grav:0,noise:RR(0.05,0.2),rot:pick([0,90])})
};

export const THEME_NAMES = Object.keys(THEMES);
